from types import TracebackType
from mte.protocols import AsyncContextManager
from mte.json import JsonType,PythonJsonType

class HTTPError(Exception): ...
class RequestError(HTTPError): ...
class TransportError(RequestError): ...
class NetworkError(TransportError): ...
class ConnectError(NetworkError): ...

class Response:
    @property
    def text(self) -> str: ...
    @property
    def content(self) -> bytes: ...
    def json(self) -> JsonType: ...
    @property
    def status_code(self) -> int: ...

class AsyncClient(AsyncContextManager[AsyncClient]):
    async def get(
        self,
        url: str,
        *,
        data: dict[str, str] = ...,
        json: PythonJsonType = ...,
        auth: tuple[str, str] | None = ...,
        params: dict[str, str] = ...
    ) -> Response: ...
    async def post(
        self,
        url: str,
        *,
        data: dict[str, str] = ...,
        json: PythonJsonType = ...,
        auth: tuple[str, str] | None = ...,
        params: dict[str, str] = ...
    ) -> Response: ...
    async def __aenter__(self) -> AsyncClient: ...
    async def __aexit__(
        self,
        __exc_type: type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
    ) -> bool | None: ...

def get(
    url: str,
    *,
    data: dict[str, str] = ...,
    json: PythonJsonType = ...,
    auth: tuple[str, str] | None = ...
) -> Response: ...
def post(
    url: str,
    *,
    data: dict[str, str] = ...,
    json: PythonJsonType = ...,
    auth: tuple[str, str] | None = ...
) -> Response: ...
