from contextlib import AbstractAsyncContextManager
from types import TracebackType
from typing import Any

class Response:
    @property
    def text(self) -> str: ...
    @property
    def content(self) -> bytes: ...
    def json(self) -> Any: ...

class AsyncClient(AbstractAsyncContextManager[AsyncClient]):
    async def get(self, url: str, *, data: dict[str, str] = ...) -> Response: ...
    async def post(self, url: str, *, data: dict[str, str] = ...) -> Response: ...
    def __aexit__(
        self,
        __exc_type: type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
    ) -> bool | None: ...

def get(url: str, *, data: dict[str, str] = ...) -> Response: ...
def post(url: str, *, data: dict[str, str] = ...) -> Response: ...
