from collections.abc import Iterator

class dotdict:
    def __getitem__(self, key: str) -> int: ...
    def __getattr__(self, key: str) -> int: ...

class ELF:
    symbols: dotdict
    libc: ELF
    path: str
    def __init__(self, path: str) -> None: ...
    def write(self, address: int, data: bytes) -> None: ...
    def read(self, address: int, count: int) -> bytes: ...
    def save(self, path: str) -> None: ...
    def search(
        self, needle: bytes, writable: bool = ..., executable: bool = ...
    ) -> Iterator[int]: ...
