from numpy.typing import NDArray, ArrayLike
from mte.typevar import T

def fft(a: ArrayLike[complex]) -> NDArray[complex]: ...
def ifft(a: ArrayLike[complex]) -> NDArray[complex]: ...
def fftfreq(n: int, d: float) -> NDArray[float]: ...
def fftshift(x: ArrayLike[T]) -> NDArray[T]: ...
def ifftshift(x: ArrayLike[T]) -> NDArray[T]: ...
def fft2(a: ArrayLike[complex]) -> NDArray[complex]: ...
def ifft2(a: ArrayLike[complex]) -> NDArray[complex]: ...
