from typing import TypeVar
from .typing import DTypeLike, NDArray, ArrayLike

_T = TypeVar("_T", bound=DTypeLike)

def fft(a: ArrayLike[float]) -> NDArray[complex]: ...
def ifft(a: ArrayLike[complex]) -> NDArray[complex]: ...
def fftfreq(n: int, d: float) -> NDArray[float]: ...
def fftshift(x: ArrayLike[_T]) -> NDArray[_T]: ...
def ifftshift(x: ArrayLike[_T]) -> NDArray[_T]: ...
