from typing import TypeVar
from numpy.typing import NDArray, ArrayLike

_T = TypeVar("_T")

def fft(a: ArrayLike[complex]) -> NDArray[complex]: ...
def ifft(a: ArrayLike[complex]) -> NDArray[complex]: ...
def fftfreq(n: int, d: float) -> NDArray[float]: ...
def fftshift(x: ArrayLike[_T]) -> NDArray[_T]: ...
def ifftshift(x: ArrayLike[_T]) -> NDArray[_T]: ...
def fft2(a: ArrayLike[complex]) -> NDArray[complex]: ...
def ifft2(a: ArrayLike[complex]) -> NDArray[complex]: ...
