from collections.abc import Iterator
from .row import Row
from .result import ScalarResult
from typing import Any

class CursorResult:
    def first(self) -> Row | None: ...
    def __iter__(self) -> Iterator[Row]: ...
    def scalar(self) -> Any: ...
    def scalars(self) -> ScalarResult: ...
