from typing import Any, overload
from collections.abc import Callable

@overload
def njit[F: Callable[..., Any]](*, parallel: bool = ...) -> Callable[[F], F]: ...
@overload
def njit[F: Callable[..., Any]](signature_or_function: F) -> F: ...
@overload
def jit[
    F: Callable[..., Any]
](*, parallel: bool = ..., nopython: bool = ...) -> Callable[[F], F]: ...
@overload
def jit[F: Callable[..., Any]](signature_or_function: F) -> F: ...
@overload
def prange(stop: int, /) -> range: ...
@overload
def prange(start: int, stop: int, step: int = ...) -> range: ...
