from numpy.typing import ArrayLike

def mean_absolute_error(
    y_true: ArrayLike[float], y_pred: ArrayLike[float]
) -> float: ...
def mean_squared_error(y_true: ArrayLike[float], y_pred: ArrayLike[float]) -> float: ...
