from .development.base_component import Component

_Child = str | list[Component]

class _HTML(Component):
    def __init__(self, children: _Child = ..., id: str = ...) -> None: ...

class H1(_HTML): ...
class H2(_HTML): ...
class H3(_HTML): ...
class H4(_HTML): ...
class H5(_HTML): ...
class H6(_HTML): ...
class Div(_HTML): ...
class Br(_HTML): ...
class P(_HTML): ...
