from ._mysql import result

def connect(*, host: str, port: int, user: str, passwd: str) -> Connection: ...

class Connection:
    def query(self, query: str) -> None: ...
    def store_result(self) -> result: ...
