from numpy.typing import NDArray
from skimage.measure._measure import RegionProperties
from mte.numpy import BaseNDArray

def label[F: float](label_image: BaseNDArray[F]) -> NDArray[int]: ...
def regionprops(label_image: BaseNDArray[int]) -> list[RegionProperties]: ...
