from collections.abc import Hashable, Iterator
from typing import Any, Self


class AtlasView[N: Hashable]:
    def __iter__(self) -> Iterator[N]: ...
    def __getitem__(self, item: str) -> Any: ...
    def __setitem__(self, item: str, value: Any) -> None: ...
    def __len__(self) -> int: ...
    def __call__(self) -> Self: ...
