from collections.abc import Hashable, Iterator
from typing import Any

class AtlasView[N: Hashable]:
    def __iter__(self) -> Iterator[N]: ...
    def __getitem__(self, item: N) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
