from collections.abc import Hashable, Iterator
from typing import Any, Self


class EdgeView[N: Hashable]:
    def __iter__(self) -> Iterator[tuple[N, N]]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: tuple[N, N]) -> dict[str, Any]: ...
    def __call__(self) -> Self: ...


class NodeView[N: Hashable]:
    def __iter__(self) -> Iterator[N]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, item: N) -> dict[str, Any]: ...
    def __call__(self) -> Self: ...
