from numpy.typing import NDArray
from mte.pandas import SeriesLike

class Categorical[T](SeriesLike[int, T]):
    def __array__(self) -> NDArray[T]: ...
    def __getitem__(self, item: int) -> T: ...
    def __contains__(self, item: int, /) -> bool: ...
    def __len__(self) -> int: ...
