from pandas import Series

class CombinedDatetimelikeProperties[K]:
    @property
    def day(self) -> Series[K, int]: ...
    @property
    def month(self) -> Series[K, int]: ...
    @property
    def year(self) -> Series[K, int]: ...
