from typing import Generic, TypeVar
from collections.abc import Iterator

_T = TypeVar("_T")
_T_cov = TypeVar("_T_cov", covariant=True)

class Index(Generic[_T_cov]):
    def __contains__(self: Index[_T], value: _T, /) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T_cov]: ...
    def __getitem__(self, item: int, /) -> _T_cov: ...
