from collections.abc import Iterator

class Index[T]:
    def __contains__[T2](self: Index[T2], value: T2, /) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
    def __getitem__(self, item: int, /) -> T: ...
