from typing import Generic
from collections.abc import Iterator
from mte.typevar import T, T_co

class Index(Generic[T_co]):
    def __contains__(self: Index[T], value: T, /) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T_co]: ...
    def __getitem__(self, item: int, /) -> T_co: ...
