from numpy.typing import NDArray

def open(fp: str) -> Image: ...
def fromarray(obj: NDArray[int]) -> Image: ...

class Image:
    def __array__(self) -> NDArray[int]: ...
    def save(self, fp: str) -> None: ...
    def show(self) -> None: ...
