from numpy.typing import NDArray
from mte.numpy import BaseNDArray

def open(fp: str) -> Image: ...
def fromarray(obj: BaseNDArray[int]) -> Image: ...

class Image:
    def __array__(self) -> NDArray[int]: ...
    def save(self, fp: str) -> None: ...
    def show(self) -> None: ...
