from .controllers.media import MediaStatus
from .controllers import MediaController

class Chromecast:
    def __init__(
        self,
        cast_info: str,
        *,
        tries: int | None = ...,
        timeout: float | None = ...,
        retry_wait: float | None = ...
    ) -> None: ...
    def start(self) -> None: ...
    def wait(self, timeout: float | None = ...) -> MediaStatus | None: ...
    def join(self, timeout: float | None = ...) -> None: ...
    def set_volume_muted(self, muted: bool) -> None: ...
    def set_volume(self, volume: float) -> float: ...
    media_controller: MediaController
