from mte.yaml import YamlType, PythonYamlType
from collections.abc import Iterator, Iterable
from typing import overload, TextIO, BinaryIO

def safe_load(stream: bytes | str | TextIO | BinaryIO) -> YamlType: ...
def safe_load_all(stream: bytes | str | TextIO | BinaryIO) -> Iterator[YamlType]: ...
@overload
def safe_dump(data: PythonYamlType, stream: None = ...) -> str: ...
@overload
def safe_dump(data: PythonYamlType, stream: TextIO | BinaryIO) -> None: ...
@overload
def safe_dump_all(data: Iterable[YamlType], stream: None = ...) -> str: ...
@overload
def safe_dump_all(data: Iterable[YamlType], stream: TextIO | BinaryIO) -> None: ...
