from numpy.typing import ArrayLike

_T = ArrayLike[int | float | str | range] | int | float | str | range

def show() -> None: ...
def hist(x: _T, bins: int = ...) -> None: ...
def xlabel(xlabel: str) -> None: ...
def ylabel(ylabel: str) -> None: ...
def title(label: str) -> None: ...
def stem(x: _T, y: _T, /) -> None: ...
def step(x: _T, y: _T) -> None: ...
