from pandas import Series

class StringMethods[T]:
    def contains(self, pat: str) -> Series[T, bool]: ...
    def split(self, pat: str = ...) -> Series[T, list[str]]: ...
    def replace(self, pat: str, repl: str) -> Series[T, str]: ...
    def __getitem__(self, item: int | slice) -> Series[T, str]: ...
    def count(self, pat: str) -> Series[T, int]: ...
    def startswith(self, pat: str) -> Series[T, bool]: ...
    def endswith(self, pat: str) -> Series[T, bool]: ...
