class ArsenicError(Exception):
    """Base exception class used by arsenic."""

class OperationNotSupported(ArsenicError):
    """Exception raised for operations not supported by a given webdriver and/or browser."""

class WebdriverError(ArsenicError):
    """Base class for webdriver-side errors."""

class UnknownArsenicError(ArsenicError):
    """Exception used when there was a webdriver-side error, but arsenic could not figure out what the error was."""

class ArsenicTimeout(ArsenicError):
    """Raised when arsenic.webdriver.WebDriver.wait(), arsenic.session.Session.wait() or a higher level wait API times out."""

class NoSuchElement(WebdriverError): ...
class NoSuchFrame(WebdriverError): ...
class UnknownCommand(WebdriverError): ...
class StaleElementReference(WebdriverError): ...
class ElementNotVisible(WebdriverError): ...
class InvalidElementState(WebdriverError): ...
class UnknownError(WebdriverError): ...
class ElementNotInteractable(WebdriverError): ...
class ElementIsNotSelectable(WebdriverError): ...
class JavascriptError(WebdriverError): ...
class Timeout(WebdriverError): ...
class NoSuchWindow(WebdriverError): ...
class InvalidCookieDomain(WebdriverError): ...
class UnableToSetCookie(WebdriverError): ...
class UnexpectedAlertOpen(WebdriverError): ...
class NoSuchAlert(WebdriverError): ...
class ScriptTimeout(WebdriverError): ...
class InvalidElementCoordinates(WebdriverError): ...
class IMENotAvailable(WebdriverError): ...
class IMEEngineActivationFailed(WebdriverError): ...
class InvalidSelector(WebdriverError): ...
class MoveTargetOutOfBounds(WebdriverError): ...
