from numpy.typing import ArrayLike, NDArray

def rgb2hsv(rgb: ArrayLike[float]) -> NDArray[float]: ...
def rgb2gray(rgb: ArrayLike[float]) -> NDArray[float]: ...
def hsv2rgb(hsv: ArrayLike[float]) -> NDArray[float]: ...
