from numpy.typing import NDArray, ArrayLike
from mte.numpy import BaseNDArray

def erosion[
    F: float
](image: BaseNDArray[F], footprint: ArrayLike[float]) -> NDArray[F]: ...
def dilation[
    F: float
](image: BaseNDArray[F], footprint: ArrayLike[float]) -> NDArray[F]: ...
def closing[F: float](image: BaseNDArray[F]) -> NDArray[F]: ...
def opening[F: float](image: BaseNDArray[F]) -> NDArray[F]: ...
def area_closing[
    F: float
](image: BaseNDArray[F], area_threshold: int = ...) -> NDArray[F]: ...
