from numpy.typing import NDArray, ArrayLike
from typing import TypeVar

_T = TypeVar("_T", bound=float)

def erosion(image: NDArray[_T], footprint: ArrayLike[float]) -> NDArray[_T]: ...
def dilation(image: NDArray[_T], footprint: ArrayLike[float]) -> NDArray[_T]: ...
def closing(image: NDArray[_T]) -> NDArray[_T]: ...
def opening(image: NDArray[_T]) -> NDArray[_T]: ...
def area_closing(image: NDArray[_T], area_threshold: int = ...) -> NDArray[_T]: ...
