from numpy.typing import NDArray, ArrayLike
from mte.typevar import F
from mte.numpy import BaseNDArray

def erosion(image: BaseNDArray[F], footprint: ArrayLike[float]) -> NDArray[F]: ...
def dilation(image: BaseNDArray[F], footprint: ArrayLike[float]) -> NDArray[F]: ...
def closing(image: BaseNDArray[F]) -> NDArray[F]: ...
def opening(image: BaseNDArray[F]) -> NDArray[F]: ...
def area_closing(image: BaseNDArray[F], area_threshold: int = ...) -> NDArray[F]: ...
